### PR TITLE
feat: Fallback templates download

### PR DESCRIPTION
**Pull request by SrIzan10**
kay, this should work!

probably when this PR gets merged there can be a new version of the cli!

### CODE REVIEW

**Comment by SrIzan10** [comment]
nvm need to update mainstream in the pr 💀

**Comment by SrIzan10** [comment]
kay fixed conflicts, ready to merge

**Comment by SrIzan10** [comment]
yeah so still not

**Comment by SrIzan10** [comment]
going to rewrite this, so yeah, closing

**Comment by EvolutionX-10** [comment]
> going to rewrite this, so yeah, closing

probably keep it simple and use sourceb.in instead

**Comment by SrIzan10** [comment]
just opening up a PR hahah

**Comment by EvolutionX-10** [comment]
cool

**Comment by SrIzan10** [comment]
https://github.com/sern-handler/cli/pull/82

**Pull request closed without merging**
