### PR TITLE
fix: change file path for sern/extras

### PR DESCRIPTION
**Pull request by needhamgary**
This should fix the error opening file path
image

### CODE REVIEW

**Comment by jacoobes** [comment]
has this been reviewed locally?

**Comment by needhamgary** [comment]
I'll have it tested within  24hr from now and get back to you

**Comment by jacoobes** [comment]
Perfect, thanks!

Vào Th 7, 5 thg 8, 2023 lúc 7:41 CH Gary ***@***.***> đã viết:

**Review by jacoobes — APPROVED** [review]
Tested locally

**Review by EvolutionX-10 — APPROVED** [review]

**Pull request merged**
