### PR TITLE
feat(init): deprecate init and bump deps

### PR DESCRIPTION
**Pull request by EvolutionX-10**

### CODE REVIEW

**Comment by jacoobes** [comment]
fix lint

**Comment by EvolutionX-10** [comment]
Will do in some time

**Comment by jacoobes** [comment]
Might be a workflow things. I tested locally, and it works for me. There's also warnings of a bad engine in the ci logs, waht do you think?

**Comment by EvolutionX-10** [comment]
looks like it's checking the main which is weird, lemme merge and see

**Pull request merged**
