### PR TITLE
Add PNPM Package Manager

### PR DESCRIPTION
**Pull request by DuroCodes**
- Adds the `pnpm` package manager for `sern init`.

### CODE REVIEW

**Comment by EvolutionX-10** [comment]
I'll review it later, make sure you've tested it properly

**Review by jacoobes — APPROVED** [review]

**Comment by DuroCodes** [comment]
I've tested it, maybe it would be helpful to add a check if the user has multiple package managers instead of all of them instead. That way if someone has only NPM and Yarn, it would still prompt them

**Comment by jacoobes** [comment]
my bad forgot to merge

**Comment by jacoobes** [comment]
closing because stale

**Pull request closed without merging**
